// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $city_index from "./routes/city/index.tsx";
import * as $dog_index from "./routes/dog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $user_index from "./routes/user/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/city/index.tsx": $city_index,
    "./routes/dog/index.tsx": $dog_index,
    "./routes/index.tsx": $index,
    "./routes/user/index.tsx": $user_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
